export const countries = [
  { name: "Afghanistan", code: "AF" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "Andorra", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Brazil", code: "BR" },
  { name: "Brunei", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo (Brazzaville)", code: "CG" },
  { name: "Congo (Kinshasa)", code: "CD" },
  { name: "Costa Rica", code: "CR" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Eswatini", code: "SZ" },
  { name: "Ethiopia", code: "ET" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Greece", code: "GR" },
  { name: "Grenada", code: "GD" },
  { name: "Guatemala", code: "GT" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Honduras", code: "HN" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Laos", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia", code: "FM" },
  { name: "Moldova", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" }
];


export const states = [
  { key: "AN", name: "Andaman and Nicobar Islands" },
  { key: "AP", name: "Andhra Pradesh" },
  { key: "AR", name: "Arunachal Pradesh" },
  { key: "AS", name: "Assam" },
  { key: "BR", name: "Bihar" },
  { key: "CH", name: "Chandigarh" },
  { key: "CT", name: "Chhattisgarh" },
  { key: "DN", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { key: "DL", name: "Delhi" },
  { key: "GA", name: "Goa" },
  { key: "GJ", name: "Gujarat" },
  { key: "HR", name: "Haryana" },
  { key: "HP", name: "Himachal Pradesh" },
  { key: "JK", name: "Jammu and Kashmir" },
  { key: "JH", name: "Jharkhand" },
  { key: "KA", name: "Karnataka" },
  { key: "KL", name: "Kerala" },
  { key: "LA", name: "Ladakh" },
  { key: "LD", name: "Lakshadweep" },
  { key: "MP", name: "Madhya Pradesh" },
  { key: "MH", name: "Maharashtra" },
  { key: "MN", name: "Manipur" },
  { key: "ML", name: "Meghalaya" },
  { key: "MZ", name: "Mizoram" },
  { key: "NL", name: "Nagaland" },
  { key: "OR", name: "Odisha" },
  { key: "PY", name: "Puducherry" },
  { key: "PB", name: "Punjab" },
  { key: "RJ", name: "Rajasthan" },
  { key: "SK", name: "Sikkim" },
  { key: "TN", name: "Tamil Nadu" },
  { key: "TG", name: "Telangana" },
  { key: "TR", name: "Tripura" },
  { key: "UP", name: "Uttar Pradesh" },
  { key: "UT", name: "Uttarakhand" },
  { key: "WB", name: "West Bengal" }
];


export const districts = [
  { district_id: 1, district_name: "Ahmednagar" },
  { district_id: 2, district_name: "Akola" },
  { district_id: 3, district_name: "Amravati" },
  { district_id: 4, district_name: "Aurangabad" },
  { district_id: 5, district_name: "Beed" },
  { district_id: 6, district_name: "Bhandara" },
  { district_id: 7, district_name: "Buldhana" },
  { district_id: 8, district_name: "Chandrapur" },
  { district_id: 9, district_name: "Dhule" },
  { district_id: 10, district_name: "Gadchiroli" },
  { district_id: 11, district_name: "Gondia" },
  { district_id: 12, district_name: "Hingoli" },
  { district_id: 13, district_name: "Jalgaon" },
  { district_id: 14, district_name: "Jalna" },
  { district_id: 15, district_name: "Kolhapur" },
  { district_id: 16, district_name: "Latur" },
  { district_id: 17, district_name: "Mumbai City" },
  { district_id: 18, district_name: "Mumbai Suburban" },
  { district_id: 19, district_name: "Nagpur" },
  { district_id: 20, district_name: "Nanded" },
  { district_id: 21, district_name: "Nandurbar" },
  { district_id: 22, district_name: "Nasik" },
  { district_id: 23, district_name: "Osmanabad" },
  { district_id: 24, district_name: "Palghar" },
  { district_id: 25, district_name: "Parbhani" },
  { district_id: 26, district_name: "Pune" },
  { district_id: 27, district_name: "Raigad" },
  { district_id: 28, district_name: "Ratnagiri" },
  { district_id: 29, district_name: "Sangli" },
  { district_id: 30, district_name: "Satara" },
  { district_id: 31, district_name: "Sindhudurg" },
  { district_id: 32, district_name: "Solapur" },
  { district_id: 33, district_name: "Thane" },
  { district_id: 34, district_name: "Wardha" },
  { district_id: 35, district_name: "Washim" },
  { district_id: 36, district_name: "Yavatmal" }
];
